class TrainingLogTable:

    def __init__(self):
        pass

    TABLE_NAME = "TrainingLog"

    ID = "Id"
    ATHLETE_ID = "Athlete_Id"
    TYPE_ID = "Type_ID"
    LOG_DATE = "Log_Date"
    LOG_TIME = "Log_Time"
    LOG_NAME = "Log_Name"
    LOG_DESC = "Log_Description"
    ATHLETES_COMMENTS = "Athletes_Comments"
    COACHES_COMMENTS = "Coaches_Comments"
    WORKOUT_COMMENTS = "Workout_Comments"
    DURATION_PLANNED = "Duration_Planned"
    DURATION_ACTUAL = "Duration_Actual"
    DISTANCE_PLANNED = "Distance_Planned"
    DISTANCE_ACTUAL = "Distance_Actual"
    DISTANCE_UNIT = "Distance_Unit"
    HR_RESTING_PLANNED = "HR_Resting_Planned"
    HR_AVG_PLANNED = "HR_Avg_Planned"
    HR_MAX_PLANNED = "HR_Max_Planned"
    HR_RESTING_ACTUAL = "HR_Resting_Actual"
    HR_AVG_ACTUAL = "HR_Avg_Actual"
    HR_MAX_ACTUAL = "HR_Max_Actual"
    WATTS_AVG_PLANNED = "Watts_Avg_Planned"
    WATTS_MAX_PLANNED = "Watts_Max_Planned"
    WATTS_AVG_ACTUAL = "Watts_Avg_Actual"
    WATTS_MAX_ACTUAL = "Watts_Max_Actual"
    RPE_PLANNED = "RPE_Planned"
    RPE_ACTUAL = "RPE_Actual"
    HR_ZONE1_TIME = "HR_Zone1_Time"
    HR_ZONE2_TIME = "HR_Zone2_Time"
    HR_ZONE3_TIME = "HR_Zone3_Time"
    HR_ZONE4_TIME = "HR_Zone4_Time"
    HR_ZONE5_TIME = "HR_Zone5_Time"
    HR_ZONE6_TIME = "HR_Zone6_Time"
    CALORIES_BURNED = "Calories_Burned"
    SLEEP_QUALITY = "Sleep_Quality"
